version = 0.1

[default.deploy.parameters]
stack_name = "cp-crosstown-pdf-compliance"
resolve_s3 = true
s3_prefix = "cp-crosstown-pdf-compliance"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM CAPABILITY_NAMED_IAM"
parameter_overrides = "ClientPrefix=\"cp\""
image_repositories = []

[default.global.parameters]
region = "us-east-1"
